### ISSUE TITLE
Question: Audio Selection

### ISSUE THREAD

**Issue by ninokierulf** [vimeo/VIMVideoPlayer#21]
Hi, I want to add audio selection in the player without modifying your code.
What would be the clean way to approach this.

PS: I know how to change the audio via selectMediaOption. I just want to know how you guys would approach this. Would you place the code in the ViewController, in the delegate videoPlayerViewIsReadyToPlayVideo? or is there a cleaner approach?

PPS: I don't have deliverables, I'm just trying to learn how to make simple and clean code. And I like your approach.

**Comment by ninokierulf** [comment]
For the moment, this is my approach.
I implemented it as a category of the player

```
@implementation VIMVideoPlayer (AudioSelection)

- (void)requestAudioChangeWithSelection:(AVMediaSelectionOption *(^)( AVMediaSelectionGroup * ))selectionGroup
                             completion:(void (^)())completion {

    AVPlayerItem *currentItem = [self.player currentItem];
    AVMediaSelectionGroup* audioSelectionGroup = [[currentItem asset] mediaSelectionGroupForMediaCharacteristic: AVMediaCharacteristicAudible];

    if(selectionGroup) {
        AVMediaSelectionOption *optionSelected = selectionGroup(audioSelectionGroup);
        [currentItem selectMediaOption:optionSelected inMediaSelectionGroup:audioSelectionGroup];
    }
    
    if(completion) { completion(); }
};

@end
```

Any comments would be helpful. Thanks

**Comment by alfiehanssen** [comment]
@ninokierulf So sorry for the delay, a category is a nice approach to this. Maybe it's something we can eventually include in the player itself. 

Consider adding inline documentation above your method to describe what the method does and why it's useful. Consider also creating a pull request against `master` to formally include it in the repo.
