### ISSUE TITLE
Play multi videos

### ISSUE THREAD

**Issue by thienchau** [vimeo/VIMVideoPlayer#24]
Hi,
I have a list of vimeo, my flow is:
for vimeo in list {
fetch vimeo direct url 
play vimeo with VIMVideoPlayer
} 

I have a VIMVideoPlayer to reuse
But I don't known how to switch to other url? I try this, but not work:
- (void)playVideoVimeo: (NSURL*)url {
    [_vimeoPlayerView.player setURL:url];
    [_vimeoPlayerView.player play];
}

I tried to new 1 view for every video but I got other issue: the audio go first 2s after then is image. So with video about 2s, I don't see anything, only hear the sound.

I use 
xcode 6.4
simulator 8.4

Thanks.

**Comment by huebnerob** [comment]
Hi @thienchau, 

Before playing any new media in a VIMVideoPlayer object with existing content, you should call `[videoPlayer reset]`.  This should restore the player to a clean state and should enable a second video to be played without issue.

**Comment by thienchau** [comment]
I've tried this but no luck:

VIMVideoPlayerView *vimeoPlayerView;


- (void)playVideoVimeo: (NSURL*)url {
    [_vimeoPlayerView.player reset];
    [_vimeoPlayerView.player setURL:url];
    [_vimeoPlayerView.player play];
}

**Comment by thienchau** [comment]
Hi @huebnerob,
seems I found root cause I used YTVimeoExtractor, It return to non-UI thread.
I updated to run on UIThread and it works.

dispatch_async(dispatch_get_main_queue(),{
                if error == nil {
                    self.myVideoPlayer.playVideoVimeo(url)
                }
            })

Thanks for your support.
