### ISSUE TITLE
Where I get URL to mp4

### ISSUE THREAD

**Issue by parfeon** [vimeo/VIMVideoPlayer#34]
From docs it is unclear where I should get reference on MP4 file.
I don't want to use https://player.vimeo.com/video/<video_id>/config to get this information and have strong believe what there is more preferable and _legal_ ay to get it.

How do I get path to MP4 which can be used with this player?

Best regards,
Sergey

**Comment by alfiehanssen** [comment]
Hi @parfeon, check out the API docs: https://developer.vimeo.com/api/endpoints/videos

You can get progressive playback URLs from the video object JSON response. However you must have a Vimeo "Pro" account.

**Comment by parfeon** [comment]
@alfiehanssen Because there is not a single word about such API behaviour in docs - it takes a lot of time to figure out what is going on. At least add somewhere API usage under PRO account and how it should be used.

For example, to use my manually generated access token I had to create VIMAccountNew and fill it by my own hands. It will be great if VIMSession will just have method to configure with existing access token.

Best regards,
Sergey

**Comment by alfiehanssen** [comment]
@parfeon, you are correct, so sorry for the confusion. Apparently documentation pertaining to this is soon to be added to developer.vimeo.com (cc @Dashron) and I just [pull requested](https://github.com/vimeo/VIMVideoPlayer/pull/35) some updates to the README to hopefully make things easier for people.
